#version: '3.9'

services:
    mysql-adverts:
        container_name: mysql-adverts
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './database/app-mysql-data:/var/lib/mysql'

#        networks:
#            - app-herd
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

# При использовании Herd, контейнер базы данных должен запускаться во внутренней сети по умолчанию. Мои сети Herd не видит.

#networks:
#    app-herd:
#        name: app-herd
#        driver: bridge
